export default {
  fields: [{
    id: 'field1',
    name: 'column1',
    field: 'field1',
    sort: 1,
    hidden: false,
    type: 'text',
    dateFormat: 'YYYYMMDD',
    realType: 'date'
  }, {
    id: 'field2',
    name: 'column2',
    field: 'field2',
    sort: 2,
    hidden: false,
    type: 'date',
    dateFormat: 'YYYYMMDD',
    realType: 'date'
  }, {
    id: 'field3',
    name: 'column3',
    field: 'field3',
    sort: 3,
    hidden: false,
    type: 'text',
    dateFormat: 'YYYYMMDD',
    realType: 'date'
  }, {
    id: 'field4',
    name: 'column4',
    field: 'field4',
    sort: 4,
    hidden: false,
    type: 'text',
    dateFormat: 'YYYYMMDD',
    realType: 'date'
  }]
}
